### ISSUE TITLE
configparser.NoSectionError: No section: 'global'

### ISSUE THREAD

**Issue by Zeroto521** [brandonxiang/psm#3]
## 问题

```cmd
>>> python -m psm show
Traceback (most recent call last):
  File "C:\Software\Miniconda3\envs\data\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Software\Miniconda3\envs\data\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Software\Miniconda3\envs\data\lib\site-packages\psm.py", line 77, in <module>
    main()
  File "C:\Software\Miniconda3\envs\data\lib\site-packages\psm.py", line 73, in main
    show()
  File "C:\Software\Miniconda3\envs\data\lib\site-packages\psm.py", line 57, in show
    index_url = conf.get("global", "index-url")
  File "C:\Software\Miniconda3\envs\data\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Software\Miniconda3\envs\data\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'global'
```
## 环境

Python 3.7.3

## 原因

不存在 `~/.pip/pip.config` 仅存在 `~/pip/pip.ini` 则可能是版本问题？

**Comment by Zeroto521** [comment]
可以看看[这个测试](https://travis-ci.com/Zeroto521/psm/builds/113959919)

```python
def show():
    conf = ConfigParser()
    # FIXME: about platform
    # linux: ?
    # window: ~/pip/pip.ini
    # mac: ?
    path = os.path.expanduser("~/.pip/pip.conf")
    if os.path.exists(path):
        conf.read(path)
        index_url = conf.get("global", "index-url")
        for key, url in sources.items():
            if index_url == url:
                msg = "Current source is %s" % key
                break
        else:
            msg = "Unknown source"
    else:
        msg = "pip file is not existed."

    print(msg)
```

这个pip配置文件似乎很不明确。

window 环境下，py3.7 是 ``~/pip/pip.ini`

linux 环境下，`.ini`，`.conf` 文件竟然都不是
